
import { WordItem } from './types';

export const WORD_DATA: WordItem[] = [
  // 1. 한자어 순화어
  { id: 'h1', original: '가료(加療)', purified: ['치료', '고침', '병 고침'], category: '한자어' },
  { id: 'h2', original: '가처분(假處分)', purified: ['임시 처분'], category: '한자어' },
  { id: 'h3', original: '구거(溝渠)', purified: ['도랑'], category: '한자어' },
  { id: 'h4', original: '납득(納得)', purified: ['이해'], category: '한자어' },
  { id: 'h5', original: '노견(路肩)', purified: ['갓길'], category: '한자어' },
  { id: 'h6', original: '노변(路邊)', purified: ['길가'], category: '한자어' },
  { id: 'h7', original: '대합실(待合室)', purified: ['맞이방', '기다리는 곳'], category: '한자어' },
  { id: 'h8', original: '망년회(忘年會)', purified: ['송년 모임', '송년회'], category: '한자어' },
  { id: 'h9', original: '매점(買占)', purified: ['사재기'], category: '한자어' },
  { id: 'h10', original: '명도(明渡)', purified: ['내줌', '넘겨줌'], category: '한자어' },
  { id: 'h11', original: '몽리(蒙利)', purified: ['수혜', '덕 봄', '이익 얻음'], category: '한자어' },
  { id: 'h12', original: '미망인(未亡人)', purified: ['고인의 부인'], category: '한자어' },
  { id: 'h13', original: '미연(未然)에', purified: ['미리'], category: '한자어' },
  { id: 'h14', original: '별첨(別添)', purified: ['따로 붙임'], category: '한자어' },
  { id: 'h15', original: '불하(拂下)', purified: ['매각'], category: '한자어' },
  { id: 'h16', original: '산입(算入)', purified: ['포함', '셈에 넣음'], category: '한자어' },
  { id: 'h17', original: '수순(手順)', purified: ['순서', '절차', '차례'], category: '한자어' },
  { id: 'h18', original: '시건장치(施鍵裝置)', purified: ['잠금장치', '자물쇠 장치'], category: '한자어' },
  { id: 'h19', original: '시말서(始末書)', purified: ['경위서'], category: '한자어' },
  { id: 'h20', original: '양생(養生)', purified: ['굳히기'], category: '한자어' },
  { id: 'h21', original: '은닉(隱匿)', purified: ['감춤', '숨김'], category: '한자어' },
  { id: 'h22', original: '익일(翌日)', purified: ['다음 날', '이튿날'], category: '한자어' },
  { id: 'h23', original: '일부인(日附印)', purified: ['날짜 도장'], category: '한자어' },
  { id: 'h24', original: '잔반(殘飯)', purified: ['남은 밥', '음식 찌꺼기'], category: '한자어' },
  { id: 'h25', original: '지득(知得)하다', purified: ['알게 되다', '알다'], category: '한자어' },
  { id: 'h26', original: '징구(徵求)', purified: ['걷기', '거두기', '청구'], category: '한자어' },
  { id: 'h27', original: '착수(着手)', purified: ['시작'], category: '한자어' },
  { id: 'h28', original: '촉수엄금(觸手嚴禁)', purified: ['손대지 마십시오'], category: '한자어' },
  { id: 'h29', original: '부의(附議)', purified: ['토의에 부침'], category: '한자어' },
  { id: 'h30', original: '불입(拂入)', purified: ['냄', '납입'], category: '한자어' },
  { id: 'h31', original: '학부형(學父兄)', purified: ['학부모'], category: '한자어' },
  { id: 'h32', original: '해태(懈怠)', purified: ['게으름', '태만'], category: '한자어' },

  // 2. 외래어 순화어
  { id: 'w1', original: '노가다', purified: ['현장 근로', '현장 근로자'], category: '외래어' },
  { id: 'w2', original: '다다기', purified: ['다짐', '다진 양념'], category: '외래어' },
  { id: 'w3', original: '무데뽀', purified: ['막무가내'], category: '외래어' },
  { id: 'w4', original: '바께쓰', purified: ['양동이', '들통'], category: '외래어' },
  { id: 'w5', original: '비까번쩍', purified: ['번쩍번쩍'], category: '외래어' },
  { id: 'w6', original: '사시미', purified: ['생선회'], category: '외래어' },
  { id: 'w7', original: '지라시', purified: ['선전지', '낱장 광고'], category: '외래어' },
  { id: 'w8', original: '쿠사리', purified: ['핀잔'], category: '외래어' },
  { id: 'w9', original: '레시피(recipe)', purified: ['조리법'], category: '외래어' },
  { id: 'w10', original: '론칭쇼(launching show)', purified: ['신제품 발표회'], category: '외래어' },
  { id: 'w11', original: '리메이크(remake)', purified: ['재구성', '원작 재구성'], category: '외래어' },
  { id: 'w12', original: '리플(reply)', purified: ['댓글'], category: '외래어' },
  { id: 'w13', original: '마켓(market)', purified: ['시장'], category: '외래어' },
  { id: 'w14', original: '멀티탭(multi-tap)', purified: ['모둠전원꽂이'], category: '외래어' },
  { id: 'w15', original: '메모리(memory)', purified: ['기억 장치'], category: '외래어' },
  { id: 'w16', original: '모멘텀(momentum)', purified: ['전환 국면'], category: '외래어' },
  { id: 'w17', original: '네티즌(netizen)', purified: ['누리꾼'], category: '외래어' },
  { id: 'w18', original: '뉘앙스(nuance)', purified: ['어감', '말맛', '느낌'], category: '외래어' },
  { id: 'w19', original: '데드라인(deadline)', purified: ['한계선', '최종 한계', '마감', '기한'], category: '외래어' },
  { id: 'w20', original: '데뷔(debut)', purified: ['등단', '등장', '첫등장', '첫무대', '첫등단'], category: '외래어' },
  { id: 'w21', original: '데스크(desk)', purified: ['부서장', '취재 책임자', '책상'], category: '외래어' },
  { id: 'w22', original: '디스카운트(discount)', purified: ['에누리', '할인'], category: '외래어' },
  { id: 'w23', original: '엘레강스(elegance)', purified: ['우아', '고상'], category: '외래어' },
  { id: 'w24', original: '오픈마켓(Open Market)', purified: ['열린 시장', '열린 장터'], category: '외래어' },
  { id: 'w25', original: '웨딩플래너(wedding planner)', purified: ['결혼설계사'], category: '외래어' },
  { id: 'w26', original: '인센티브(incentive)', purified: ['성과급', '유인책', '특전'], category: '외래어' },
  { id: 'w27', original: '정크푸드(junk food)', purified: ['부실음식', '부실식품'], category: '외래어' },
  { id: 'w28', original: '카메라맨(cameraman)', purified: ['사진사', '사진 기자'], category: '외래어' },
  { id: 'w29', original: '컨트롤 타워(control tower)', purified: ['통제탑', '지휘 본부', '사령탑'], category: '외래어' },
  { id: 'w30', original: '무빙워크(moving sidewalk)', purified: ['자동길'], category: '외래어' },
  { id: 'w31', original: '발레파킹(valet parking)', purified: ['대리주차'], category: '외래어' },
  { id: 'w32', original: '보드마커(board marker)', purified: ['칠판펜'], category: '외래어' },
  { id: 'w33', original: '선루프(sunroof)', purified: ['지붕창'], category: '외래어' },
  { id: 'w34', original: '스크린 도어(screen door)', purified: ['안전문'], category: '외래어' },
  { id: 'w35', original: '아이콘(Icon)', purified: ['상징', '상징물', '그림 단추'], category: '외래어' },
  { id: 'w36', original: '타임캡슐(time capsule)', purified: ['기억상자'], category: '외래어' },
  { id: 'w37', original: '트러블(trouble)', purified: ['말썽', '충돌', '고장', '문제점', '불화'], category: '외래어' },
  { id: 'w38', original: '트렌드(trend)', purified: ['유행', '경향'], category: '외래어' },
  { id: 'w39', original: '팁(tip)', purified: ['도움말', '봉사료'], category: '외래어' },
  { id: 'w40', original: '팝업 창(pop-up 窓)', purified: ['알림창'], category: '외래어' },
  { id: 'w41', original: '패스(pass)', purified: ['통과', '합격'], category: '외래어' },
  { id: 'w42', original: '플래카드(placard)', purified: ['펼침막', '현수막'], category: '외래어' },

  // 3. 최신 추가된 순화어 (ICT, 경제 등)
  { id: 'n1', original: 'ICT', purified: ['정보문화기술'], category: '최신 순화어' },
  { id: 'n2', original: '뉴 스페이스(new space)', purified: ['민간 우주 개발'], category: '최신 순화어' },
  { id: 'n3', original: '도어스텝핑(doorstepping)', purified: ['출근길 문답', '약식 문답'], category: '최신 순화어' },
  { id: 'n4', original: '디제라티(digerati)', purified: ['디지털 지식인'], category: '최신 순화어' },
  { id: 'n5', original: '디지털 트윈(digital twin)', purified: ['가상 모형'], category: '최신 순화어' },
  { id: 'n6', original: '멀티데믹(multi pandemic)', purified: ['감염병 복합 유행'], category: '최신 순화어' },
  { id: 'n7', original: '미코노미(meconomy)', purified: ['자기중심 소비'], category: '최신 순화어' },
  { id: 'n8', original: '빅 테크(big tech)', purified: ['정보 기술 대기업'], category: '최신 순화어' },
  { id: 'n9', original: '비투비(B2B)', purified: ['기업 간 거래'], category: '최신 순화어' },
  { id: 'n10', original: '스태그플레이션(stagflation)', purified: ['고물가 경기 침체'], category: '최신 순화어' },
  { id: 'n11', original: '아이오티(IOT)', purified: ['사물 인터넷'], category: '최신 순화어' },
  { id: 'n12', original: '에이아이(AI)', purified: ['인공 지능'], category: '최신 순화어' },
  { id: 'n13', original: '엔에프티(NFT)', purified: ['대체 불가 토큰'], category: '최신 순화어' },
  { id: 'n14', original: '애그테크', purified: ['첨단 농업 기술'], category: '최신 순화어' },
  { id: 'n15', original: 'ESG 경영', purified: ['환경 사회 투명 경영', '환경·사회·투명 경영'], category: '최신 순화어' },
  { id: 'n16', original: '임팩트 비즈니스', purified: ['사회 가치 병행 사업'], category: '최신 순화어' },
  { id: 'n17', original: '칠링 이펙트(chilling effect)', purified: ['위축 효과'], category: '최신 순화어' },
  { id: 'n18', original: '코워킹 스페이스(coworking space)', purified: ['공유 업무 공간'], category: '최신 순화어' },
  { id: 'n19', original: '큐레이션 커머스(curation commerce)', purified: ['소비자 맞춤 상거래'], category: '최신 순화어' },
  { id: 'n20', original: '피크 아웃(peak out)', purified: ['하락 전환'], category: '최신 순화어' },
];
